Briareos\AclBundle\Entity\AclPermission:
    type: entity
    table: acl__permission
    repositoryClass: Briareos\AclBundle\Entity\AclPermissionRepository
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        description:
            type: string
            length: 255
            nullable: true
        secure:
            type: boolean
        weight:
            type: integer
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel
    manyToOne:
        parent:
            targetEntity: Briareos\AclBundle\Entity\AclPermission
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: SET NULL
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: Briareos\AclBundle\Entity\AclPermission
            mappedBy: parent
            orderBy:
                left: ASC
    lifecycleCallbacks: {  }
