Briareos\AclBundle\Entity\AclRole:
    type: entity
    table: acl__role
    repositoryClass: Briareos\AclBundle\Entity\AclRoleRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
        internalRole:
            type: integer
            nullable: true
    manyToMany:
        subjects:
            targetEntity: Briareos\AclBundle\Entity\AclSubjectInterface
            mappedBy: aclRoles
        permissions:
            targetEntity: Briareos\AclBundle\Entity\AclPermission
            joinTable:
                name: acl__role_permission
                joinColumns:
                    aclRole:
                        name: aclRole_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    permission:
                        name: permission_id
                        referencedColumnName: id
                        onDelete: CASCADE
    lifecycleCallbacks: {  }
